name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Build Project
      run: |
          cd googletest       
          mkdir build          
          cd build 
          cmake ..            
          cmake -Dgtest_build_tests=on -DCMAKE_INSTALL_PREFIX=. ..
          make; make install


    - name: Run Test
      run: |
          mkdir build
          cd build/
          make
          ./test
